"""
Configuration — Nifty50 Gamma Scalp Strategy Parameters
"""

# Entry Conditions
RV_WINDOW_DAYS = 5
RV_IV_EDGE_MIN = 0.05
RV_IV_EDGE_MAX = 0.10
IV_ENTRY_PERCENTILE = 65

# Delta Hedging
DELTA_HEDGE_BAND = 0.25
SPOT_MOVE_THRESHOLD = 0.0025

# Retail-Hardened Filters
FIRST_15M_MOVE_THRESHOLD = 0.0020   # Min first-15-min move to enter
ROUND_TRIP_COST = 285.0              # Estimated round-trip cost (fees + slippage)
ECONOMIC_MULTIPLIER = 4.0            # Hedge only if capture >= K× cost
HEDGE_COOLDOWN_MINUTES = 7
MAX_DAILY_HEDGES = 30

# Intraday Variance Checkpoints
NOON_RV_THRESHOLD = 0.45            # 12:30 PM: reduce 50% if RV < 45% of IV
AFTERNOON_RV_THRESHOLD = 0.70       # 2:30 PM: exit if RV < 70% of IV

# P&L Exits
PROFIT_TARGET = 0.50
MAX_LOSS = -0.30

# Volatility Exits
IV_DROP_EXIT = 0.08

# Directional Pinning Exit
DELTA_PIN_THRESHOLD = 0.50
DELTA_PIN_DURATION_MINUTES = 30

# Option Parameters
TIME_TO_EXPIRY = 7
RISK_FREE_RATE = 0.06
STRIKE_INTERVAL = 50

# Data Parameters
TIMEFRAME = '5min'
BACKTEST_DAYS = 30

# Risk Management
MAX_POSITIONS = 1
POSITION_SIZE = 1

# Volatility Calculation
HV_WINDOW = 20
IV_HV_MULTIPLIER = 1.2

# Transaction Costs
FUTURES_COMMISSION = 20
OPTIONS_COMMISSION = 50
SLIPPAGE_BPS = 5

# Greeks
MIN_GAMMA_THRESHOLD = 0.001
MIN_TIME_VALUE = 10

# Strategy Presets
CONSERVATIVE = {
    'DELTA_HEDGE_BAND': 0.20,
    'SPOT_MOVE_THRESHOLD': 0.002,
    'RV_IV_EDGE_MIN': 0.07,
    'RV_IV_EDGE_MAX': 0.12,
    'IV_ENTRY_PERCENTILE': 55,
    'PROFIT_TARGET': 0.30,
    'MAX_LOSS': -0.20,
    'IV_DROP_EXIT': 0.06,
    'FIRST_15M_MOVE_THRESHOLD': 0.0025,
    'ROUND_TRIP_COST': 285.0,
    'ECONOMIC_MULTIPLIER': 5.0,
    'HEDGE_COOLDOWN_MINUTES': 10,
    'MAX_DAILY_HEDGES': 20,
}

AGGRESSIVE = {
    'DELTA_HEDGE_BAND': 0.30,
    'SPOT_MOVE_THRESHOLD': 0.003,
    'RV_IV_EDGE_MIN': 0.03,
    'RV_IV_EDGE_MAX': 0.15,
    'IV_ENTRY_PERCENTILE': 70,
    'PROFIT_TARGET': 0.75,
    'MAX_LOSS': -0.40,
    'IV_DROP_EXIT': 0.10,
    'FIRST_15M_MOVE_THRESHOLD': 0.0015,
    'ROUND_TRIP_COST': 285.0,
    'ECONOMIC_MULTIPLIER': 3.0,
    'HEDGE_COOLDOWN_MINUTES': 5,
    'MAX_DAILY_HEDGES': 40,
}

# Market Condition Overrides
LOW_VOL_PARAMS = {
    'IV_ENTRY_PERCENTILE': 70,
    'TIME_TO_EXPIRY': 14,
    'DELTA_HEDGE_BAND': 0.20,
    'RV_IV_EDGE_MIN': 0.03,
}

HIGH_VOL_PARAMS = {
    'IV_ENTRY_PERCENTILE': 50,
    'TIME_TO_EXPIRY': 3,
    'DELTA_HEDGE_BAND': 0.30,
    'RV_IV_EDGE_MIN': 0.08,
}

TRENDING_PARAMS = {
    'DELTA_HEDGE_BAND': 0.20,
    'DELTA_PIN_DURATION_MINUTES': 20,
    'PROFIT_TARGET': 0.40,
    'MAX_LOSS': -0.25,
}

RANGE_BOUND_PARAMS = {
    'DELTA_HEDGE_BAND': 0.35,
    'SPOT_MOVE_THRESHOLD': 0.004,
    'PROFIT_TARGET': 0.60,
    'MAX_LOSS': -0.35,
}
